### ISSUE TITLE
Fechas...?

### ISSUE THREAD

**Issue by frayberen** [MiguelAngelLV/ha-input-stats#3]
Hola Miguel Ángel, antes de nada agradecerte la integración. Se me ocurre, que a la hora de poder insertar por ejemplo, facturas de este año que ya se han recibido, no hay modo de modificar la fecha de entrada para asociarlas al mes correspondiente.... Alguna indicación de cómo hacerlo....?

**Comment by miguelangellv** [comment]
Pues algo que tengo pendiente. 
Hice un par de pruebas pero no salieron bien :confused: 

 Sin embargo, el componente [Spook](https://spook.boo/recorder) tiene una función lo hace, tendría que mirar cómo integrar su código.

**Comment by frayberen** [comment]
Gracias por tu respuesta Miguel. Seguiremos atentos....!!!
