### ISSUE TITLE
¿Crear botón para ingresar datos?

### ISSUE THREAD

**Issue by fsalinasc** [MiguelAngelLV/ha-input-stats#4]
Muy buenas y gracias por la integración. Estoy intentando crear un botón para llamar al servicio e ingresar los datos a incluir y no lo consigo. (Bastante torpe)
¿Algún mini tutorial que me pueda orientar? (Si es que se puede hacer)

**Comment by miguelangellv** [comment]
No sé si has visto el vídeo que publiqué el domingo: https://youtu.be/mAUWcT4IRcY

En ahí utilizo directamente el la opción desde llamar al servicio desde un card, pero si necesitas que sea específicamente con un botón, puedes guiarte por este otro vídeo:

https://youtu.be/vCMuTdzMRk8
